version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-194-188.compute-1.amazonaws.com
            database: d4dbt35da86smt
            user: ngobpoymfmhwig
            password: adfbc9d11289bd8a93d7632c9c8da354d2548f4a446cf37b2b3c8e3b454f0d45
            ssl: true
            schema: public
            port: '5432'
            migrations: true